# -*- coding: utf-8 -*-
"""Lab2REP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bx5qXI7IvyYmE9WbzSU8d6qxv5ODaJm2

# lab2 REP
"""

print("Abdul Muhaimin")

"""# **Task 1:Lists**"""

numbers = [10, 31, 45, 34, 67, 89, 38, 98]
print('original List:', numbers)

print('Sum:', sum(numbers))
print('Max:', max(numbers))
print('Min:', min(numbers))

numbers.append(100)
numbers.remove(31)

print('Updated List:', numbers)

print('Accending:', )

no = 1
result = 100
while (no < result):
  print('current no is: ', no)
  no = no+1

"""# **Task 2:Tuples**"""

fruits = ('apple', 'orange', 'bannana', 'cherry', 'mango')
print('Second element:', fruits[1])
print('Last element:', fruits[-1])

# Tuples are immutiable, so modification will give an error
# Convert tuple to list

fruit_list = list(fruits)
fruit_list[2] = 'grapes'
print('Modified List:', fruit_list)

"""# **Task 3:Sets**"""

set_a = {1,2,3,4,5}
set_b = {4,5,6,7,8}

#Union, Intersection, Difference
print('Union:', set_a)

"""# **Task 4:Dictionaries**"""

students = {'Ali':85, 'Sara':90, 'Ahmed': 78, 'Omar': 100}
#Print keys and values
print('Key:', students.keys())
print('Values:', students.values())

#Update value
students['Ali'] = 95
print('Updated Dictionary:', students)

#Delete a key-value pair
del students['Ahmed']
print('After Deletion:', students)